spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5434/dscatalog}
    username: ${DB_URL:postgres}
    password: ${DB_PASSWORD:1234567}