spring:
  jpa:
  #  properties:
  #    jakarta:
  #      persistence:
  #        schema-generation:
  #          create-source: metadata
  #          scripts:
  #            action: create
  #            create-target: create.sql
  #    hibernate:
  #      hbm2ddl:
  #        delimiter: ;
  #      jdbc:
  #        lob:
  #          non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5435/labprog
    username: postgres
    password: 123456